"""Public interface contracts. Mirror of the v1.0 spec set under docs/specs/."""

from npu_sim.interfaces.clock import IClock, IClockEvent
from npu_sim.interfaces.module import (
    MODULE_TYPE_REGEX,
    Capability,
    EnergyEstimate,
    IModule,
    LatencyEstimate,
    ModuleState,
)
from npu_sim.interfaces.numerical import (
    FIDELITY_BIT_ACCURATE,
    FIDELITY_FAST,
    FIDELITY_GOLDEN,
    ComparisonResult,
    FidelityLevel,
    INumericalModel,
    NumericDType,
    Tensor,
    Tolerance,
    ToleranceViolation,
)
from npu_sim.interfaces.operation import (
    IOperation,
    Precision,
    PrecisionKind,
    StaticOperation,
)
from npu_sim.interfaces.services import (
    IEventBus,
    InMemoryEventBus,
    InMemoryStatSink,
    IStatSink,
    StallEvent,
    StallReason,
)
from npu_sim.interfaces.transport import (
    CdcConnectionSpec,
    ConnectionSpec,
    DataType,
    IConnection,
    ITransportPort,
    PortDirection,
    PortSpec,
    ReceiveDecision,
    ReceiveResult,
    TransportResult,
    TransportStatus,
    TransportToken,
)

__all__ = [
    "MODULE_TYPE_REGEX",
    "CdcConnectionSpec",
    "Capability",
    "ComparisonResult",
    "ConnectionSpec",
    "DataType",
    "EnergyEstimate",
    "FIDELITY_BIT_ACCURATE",
    "FIDELITY_FAST",
    "FIDELITY_GOLDEN",
    "FidelityLevel",
    "IClock",
    "IClockEvent",
    "IConnection",
    "IEventBus",
    "IModule",
    "INumericalModel",
    "IOperation",
    "IStatSink",
    "ITransportPort",
    "InMemoryEventBus",
    "InMemoryStatSink",
    "LatencyEstimate",
    "ModuleState",
    "NumericDType",
    "PortDirection",
    "PortSpec",
    "Precision",
    "PrecisionKind",
    "ReceiveDecision",
    "ReceiveResult",
    "StallEvent",
    "StallReason",
    "StaticOperation",
    "Tensor",
    "Tolerance",
    "ToleranceViolation",
    "TransportResult",
    "TransportStatus",
    "TransportToken",
]
