"""verification and escalation

Revision ID: 0799686c9be7
Revises: 6099c49a2c55
Create Date: 2026-09-18 01:17:25.537891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0799686c9be7'
down_revision: Union[str, Sequence[str], None] = '6099c49a2c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=12), nullable=False),
    sa.Column('task_title', sa.String(length=120), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('revision_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_lessons_category'), ['category'], unique=False)

    op.create_table('verification_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('verifier_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('outcome', sa.String(length=12), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('revised_output', sa.Text(), nullable=False),
    sa.Column('criteria_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_orders_payer_id'), ['payer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_orders_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_orders_verifier_id'), ['verifier_id'], unique=False)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escalated_to_dispute_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('escalated_to_dispute_id')

    with op.batch_alter_table('verification_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_orders_verifier_id'))
        batch_op.drop_index(batch_op.f('ix_verification_orders_task_id'))
        batch_op.drop_index(batch_op.f('ix_verification_orders_status'))
        batch_op.drop_index(batch_op.f('ix_verification_orders_payer_id'))

    op.drop_table('verification_orders')
    with op.batch_alter_table('verification_lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_lessons_category'))

    op.drop_table('verification_lessons')
    # ### end Alembic commands ###
