"""initial schema

Revision ID: 1732119c5de4
Revises: 
Create Date: 2026-08-22 04:08:28.493083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1732119c5de4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_audits_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_audits_admin_id'), ['admin_id'], unique=False)

    op.create_table('analytics_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_events_user_id'), ['user_id'], unique=False)

    op.create_table('anchor_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('ref_type', sa.String(length=20), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_chain_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anchor_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anchor_entries_chain_hash'), ['chain_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_anchor_entries_ref_id'), ['ref_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anchor_entries_seq'), ['seq'], unique=True)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('bid_cents', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_applicant_id'), ['applicant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_task_id'), ['task_id'], unique=False)

    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blocks_blocked_id'), ['blocked_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_blocks_blocker_id'), ['blocker_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('required_cert', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('change_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('proposed_by', sa.Integer(), nullable=False),
    sa.Column('new_amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_orders_contract_id'), ['contract_id'], unique=False)

    op.create_table('circle_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('circle_id', 'user_id')
    )
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circle_members_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_circle_members_user_id'), ['user_id'], unique=False)

    op.create_table('circles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('join_policy', sa.String(length=12), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('skill_tag', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('min_credit', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('circles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_circles_owner_id'), ['owner_id'], unique=False)

    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_content_id'), ['content_id'], unique=False)

    op.create_table('contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('visibility', sa.String(length=12), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=True),
    sa.Column('linked_category', sa.String(length=50), nullable=False),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contents_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contents_circle_id'), ['circle_id'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('released_cents', sa.Integer(), nullable=False),
    sa.Column('fee_bps', sa.Integer(), nullable=False),
    sa.Column('terms', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('signed_by_requester', sa.Boolean(), nullable=False),
    sa.Column('signed_by_executor', sa.Boolean(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('deposit_cents', sa.Integer(), nullable=False),
    sa.Column('deposit_status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('funded_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_executor_id'), ['executor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_task_id'), ['task_id'], unique=True)

    op.create_table('conversation_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id')
    )
    with op.batch_alter_table('conversation_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_reads_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_reads_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    op.create_table('decomposition_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decomposition_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decomposition_templates_category'), ['category'], unique=False)

    op.create_table('decompositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('items', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decompositions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decompositions_task_id'), ['task_id'], unique=False)

    op.create_table('dispute_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispute_statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispute_statements_dispute_id'), ['dispute_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispute_statements_user_id'), ['user_id'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('opened_by', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('settlement_proposal', sa.JSON(), nullable=True),
    sa.Column('verdict_executor_share_bps', sa.Integer(), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=False),
    sa.Column('arbiter_id', sa.Integer(), nullable=True),
    sa.Column('split_base_cents', sa.Integer(), nullable=False),
    sa.Column('appealed', sa.Boolean(), nullable=False),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_disputes_task_id'), ['task_id'], unique=False)

    op.create_table('faq_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=200), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followee_id')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_follows_followee_id'), ['followee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_follows_follower_id'), ['follower_id'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_records_user_id'), ['user_id'], unique=False)

    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'invitee_id')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitations_invitee_id'), ['invitee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_task_id'), ['task_id'], unique=False)

    op.create_table('job_locks',
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('job_name')
    )
    op.create_table('knowledge_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_task_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('price_actual_cents', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('decomposition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_cards_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_cards_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_cards_source_task_id'), ['source_task_id'], unique=False)

    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_entries_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_entries_user_id'), ['user_id'], unique=False)

    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id')
    )
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_user_id'), ['user_id'], unique=False)

    op.create_table('login_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(length=200), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('matching_configs',
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('risk_flagged', sa.Boolean(), nullable=False),
    sa.Column('recalled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_contract_id'), ['contract_id'], unique=False)

    op.create_table('mission_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('tool', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('is_remedy', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mission_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_steps_mission_id'), ['mission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mission_steps_task_id'), ['task_id'], unique=False)

    op.create_table('missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('budget_cap_cents', sa.Integer(), nullable=False),
    sa.Column('spent_cents', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('completion_pct', sa.Integer(), nullable=False),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=False),
    sa.Column('last_error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_missions_owner_id'), ['owner_id'], unique=False)

    op.create_table('notification_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category')
    )
    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_prefs_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=48), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_ref', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_orders_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_orders_user_id'), ['user_id'], unique=False)

    op.create_table('payout_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('account_no', sa.String(length=64), nullable=False),
    sa.Column('holder_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('progress_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_logs_task_id'), ['task_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('handled_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=False),
    sa.Column('rating_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_task_id'), ['task_id'], unique=False)

    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_queries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_queries_term'), ['term'], unique=False)

    op.create_table('sms_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('scene', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=80), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sms_codes_phone'), ['phone'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category', 'city')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('task_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_bookmarks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_bookmarks_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_bookmarks_user_id'), ['user_id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('executor_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=False),
    sa.Column('pricing', sa.String(length=20), nullable=False),
    sa.Column('deposit_cents', sa.Integer(), nullable=False),
    sa.Column('people_needed', sa.Integer(), nullable=False),
    sa.Column('trip_share_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('address_hint', sa.String(length=120), nullable=False),
    sa.Column('address_exact', sa.String(length=200), nullable=False),
    sa.Column('visibility', sa.String(length=12), nullable=False),
    sa.Column('circle_id', sa.Integer(), nullable=True),
    sa.Column('recurrence', sa.String(length=10), nullable=False),
    sa.Column('recurred_from_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_circle_id'), ['circle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_executor_id'), ['executor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_status'), ['status'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('interests', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('privacy', sa.JSON(), nullable=False),
    sa.Column('service_rate_cents', sa.Integer(), nullable=False),
    sa.Column('available_times', sa.String(length=200), nullable=False),
    sa.Column('accepting_orders', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('real_name', sa.String(length=50), nullable=False),
    sa.Column('id_digest', sa.String(length=80), nullable=False),
    sa.Column('id_masked', sa.String(length=24), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sa.String(length=12), nullable=False),
    sa.Column('referred_by', sa.Integer(), nullable=True),
    sa.Column('referral_rewarded', sa.Boolean(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_id_digest'), ['id_digest'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_referral_code'), ['referral_code'], unique=False)

    op.create_table('vendor_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('idem_key', sa.String(length=80), nullable=True),
    sa.Column('request_digest', sa.String(length=400), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('external_ref', sa.String(length=80), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendor_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendor_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_calls_idem_key'), ['idem_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendor_calls_kind'), ['kind'], unique=False)

    op.create_table('wallet_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('available_cents', sa.Integer(), nullable=False),
    sa.Column('escrow_cents', sa.Integer(), nullable=False),
    sa.Column('frozen_cents', sa.Integer(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('withdraw_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdraw_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdraw_requests_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdraw_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdraw_requests_user_id'))

    op.drop_table('withdraw_requests')
    op.drop_table('wallet_accounts')
    with op.batch_alter_table('vendor_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendor_calls_kind'))
        batch_op.drop_index(batch_op.f('ix_vendor_calls_idem_key'))
        batch_op.drop_index(batch_op.f('ix_vendor_calls_created_at'))

    op.drop_table('vendor_calls')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_referral_code'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_id_digest'))
        batch_op.drop_index(batch_op.f('ix_users_city'))

    op.drop_table('users')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_user_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_tasks_parent_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_executor_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_creator_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_city'))
        batch_op.drop_index(batch_op.f('ix_tasks_circle_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_category'))

    op.drop_table('tasks')
    with op.batch_alter_table('task_bookmarks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_bookmarks_user_id'))
        batch_op.drop_index(batch_op.f('ix_task_bookmarks_task_id'))

    op.drop_table('task_bookmarks')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('sms_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sms_codes_phone'))

    op.drop_table('sms_codes')
    with op.batch_alter_table('search_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_queries_term'))
        batch_op.drop_index(batch_op.f('ix_search_queries_created_at'))

    op.drop_table('search_queries')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_task_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_target_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))

    op.drop_table('reports')
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_logs_task_id'))

    op.drop_table('progress_logs')
    op.drop_table('payout_accounts')
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_orders_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_status'))
        batch_op.drop_index(batch_op.f('ix_payment_orders_order_no'))

    op.drop_table('payment_orders')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('notification_prefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_prefs_user_id'))

    op.drop_table('notification_prefs')
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_missions_owner_id'))

    op.drop_table('missions')
    with op.batch_alter_table('mission_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_steps_task_id'))
        batch_op.drop_index(batch_op.f('ix_mission_steps_mission_id'))

    op.drop_table('mission_steps')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_contract_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    op.drop_table('matching_configs')
    with op.batch_alter_table('login_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_sessions_user_id'))

    op.drop_table('login_sessions')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_likes_content_id'))

    op.drop_table('likes')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_ledger_entries_contract_id'))

    op.drop_table('ledger_entries')
    with op.batch_alter_table('knowledge_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_cards_source_task_id'))
        batch_op.drop_index(batch_op.f('ix_knowledge_cards_city'))
        batch_op.drop_index(batch_op.f('ix_knowledge_cards_category'))

    op.drop_table('knowledge_cards')
    op.drop_table('job_locks')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_task_id'))
        batch_op.drop_index(batch_op.f('ix_invitations_invitee_id'))

    op.drop_table('invitations')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_records_key'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_follows_follower_id'))
        batch_op.drop_index(batch_op.f('ix_follows_followee_id'))

    op.drop_table('follows')
    op.drop_table('faq_entries')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_task_id'))
        batch_op.drop_index(batch_op.f('ix_disputes_contract_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('dispute_statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispute_statements_user_id'))
        batch_op.drop_index(batch_op.f('ix_dispute_statements_dispute_id'))

    op.drop_table('dispute_statements')
    with op.batch_alter_table('decompositions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decompositions_task_id'))

    op.drop_table('decompositions')
    with op.batch_alter_table('decomposition_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decomposition_templates_category'))

    op.drop_table('decomposition_templates')
    op.drop_table('conversations')
    with op.batch_alter_table('conversation_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_reads_conversation_id'))

    op.drop_table('conversation_reads')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_task_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_requester_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_executor_id'))

    op.drop_table('contracts')
    with op.batch_alter_table('contents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contents_circle_id'))
        batch_op.drop_index(batch_op.f('ix_contents_author_id'))

    op.drop_table('contents')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_content_id'))

    op.drop_table('comments')
    op.drop_table('cities')
    with op.batch_alter_table('circles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circles_owner_id'))

    op.drop_table('circles')
    with op.batch_alter_table('circle_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_circle_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_circle_members_circle_id'))

    op.drop_table('circle_members')
    with op.batch_alter_table('change_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_orders_contract_id'))

    op.drop_table('change_orders')
    op.drop_table('categories')
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blocks_blocker_id'))
        batch_op.drop_index(batch_op.f('ix_blocks_blocked_id'))

    op.drop_table('blocks')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_task_id'))
        batch_op.drop_index(batch_op.f('ix_applications_applicant_id'))

    op.drop_table('applications')
    with op.batch_alter_table('anchor_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anchor_entries_seq'))
        batch_op.drop_index(batch_op.f('ix_anchor_entries_ref_id'))
        batch_op.drop_index(batch_op.f('ix_anchor_entries_chain_hash'))

    op.drop_table('anchor_entries')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_name'))
        batch_op.drop_index(batch_op.f('ix_analytics_events_created_at'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('admin_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_audits_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_audits_action'))

    op.drop_table('admin_audits')
    # ### end Alembic commands ###
