"""storage uploads and progress images

Revision ID: 1bf11fee9512
Revises: 1732119c5de4
Create Date: 2026-08-22 04:20:11.707245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf11fee9512'
down_revision: Union[str, Sequence[str], None] = '1732119c5de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 已有行必须有值，否则 NOT NULL 加列会失败——server_default 只用于本次回填，
    # 新行的默认值由 ORM 侧 default=list 提供
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('images', sa.JSON(), nullable=False, server_default='[]')
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
