"""legal: contract signatures and anchor receipts

Revision ID: 2ae4a0fbafd7
Revises: 79d8990fad5a
Create Date: 2026-08-25 01:48:26.704496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ae4a0fbafd7'
down_revision: Union[str, Sequence[str], None] = '79d8990fad5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anchor_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq_from', sa.Integer(), nullable=False),
    sa.Column('seq_to', sa.Integer(), nullable=False),
    sa.Column('chain_head', sa.String(length=64), nullable=False),
    sa.Column('receipt_no', sa.String(length=120), nullable=False),
    sa.Column('authority', sa.String(length=60), nullable=False),
    sa.Column('backed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('anchor_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anchor_receipts_seq_to'), ['seq_to'], unique=False)

    op.create_table('contract_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('signer_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('contract_version', sa.Integer(), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=512), nullable=False),
    sa.Column('certificate', sa.Text(), nullable=False),
    sa.Column('timestamp_token', sa.Text(), nullable=False),
    sa.Column('algorithm', sa.String(length=32), nullable=False),
    sa.Column('reliability', sa.String(length=24), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('signed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contract_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contract_signatures_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_signatures_document_hash'), ['document_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_contract_signatures_signer_id'), ['signer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contract_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contract_signatures_signer_id'))
        batch_op.drop_index(batch_op.f('ix_contract_signatures_document_hash'))
        batch_op.drop_index(batch_op.f('ix_contract_signatures_contract_id'))

    op.drop_table('contract_signatures')
    with op.batch_alter_table('anchor_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anchor_receipts_seq_to'))

    op.drop_table('anchor_receipts')
    # ### end Alembic commands ###
