"""growth: coupons campaigns referral rewards

Revision ID: 59ea54dff9d0
Revises: 1bf11fee9512
Create Date: 2026-08-22 06:49:33.037949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ea54dff9d0'
down_revision: Union[str, Sequence[str], None] = '1bf11fee9512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('budget_cap_cents', sa.Integer(), nullable=False),
    sa.Column('spent_cents', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('percent_bps', sa.Integer(), nullable=False),
    sa.Column('max_discount_cents', sa.Integer(), nullable=False),
    sa.Column('min_order_cents', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('newcomer_only', sa.Boolean(), nullable=False),
    sa.Column('total_quota', sa.Integer(), nullable=False),
    sa.Column('issued_count', sa.Integer(), nullable=False),
    sa.Column('per_user_limit', sa.Integer(), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_coupons_campaign_id'), ['campaign_id'], unique=False)

    op.create_table('referral_rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_id', name='uq_referral_invitee')
    )
    with op.batch_alter_table('referral_rewards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_rewards_invitee_id'), ['invitee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_rewards_inviter_id'), ['inviter_id'], unique=False)

    op.create_table('user_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_id', name='uq_user_coupon_contract')
    )
    with op.batch_alter_table('user_coupons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_coupons_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_coupons_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_coupons_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_coupons_coupon_id'))

    op.drop_table('user_coupons')
    with op.batch_alter_table('referral_rewards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_rewards_inviter_id'))
        batch_op.drop_index(batch_op.f('ix_referral_rewards_invitee_id'))

    op.drop_table('referral_rewards')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_coupons_campaign_id'))

    op.drop_table('coupons')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
