"""orchestrator: review, timeline, budget split

Revision ID: 5fdf27d6d8a1
Revises: 59ea54dff9d0
Create Date: 2026-08-22 10:23:56.311072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fdf27d6d8a1'
down_revision: Union[str, Sequence[str], None] = '59ea54dff9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 已有行必须有值，否则 NOT NULL 加列会失败——server_default 只用于本次回填，
    # 新行的默认值由 ORM 侧 default= 提供
    op.create_table('mission_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mission_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mission_events_mission_id'), ['mission_id'], unique=False)

    op.create_table('step_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('missing', sa.JSON(), nullable=False),
    sa.Column('input_digest', sa.String(length=400), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_reviews_step_id'), ['step_id'], unique=False)

    with op.batch_alter_table('mission_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_step_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('acceptance', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('review_verdict', sa.String(length=10), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('review_score', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('review_missing', sa.JSON(), nullable=False, server_default='[]'))
        batch_op.create_index(batch_op.f('ix_mission_steps_parent_step_id'), ['parent_step_id'], unique=False)

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('committed_cents', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('quality_pct', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('model_calls', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_column('model_calls')
        batch_op.drop_column('quality_pct')
        batch_op.drop_column('committed_cents')

    with op.batch_alter_table('mission_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_steps_parent_step_id'))
        batch_op.drop_column('review_missing')
        batch_op.drop_column('review_score')
        batch_op.drop_column('review_verdict')
        batch_op.drop_column('acceptance')
        batch_op.drop_column('attempt')
        batch_op.drop_column('parent_step_id')

    with op.batch_alter_table('step_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_reviews_step_id'))

    op.drop_table('step_reviews')
    with op.batch_alter_table('mission_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mission_events_mission_id'))

    op.drop_table('mission_events')
    # ### end Alembic commands ###
