"""agent execution layer

Revision ID: 6099c49a2c55
Revises: f7a3c1e94b28
Create Date: 2026-09-17 08:50:23.279530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6099c49a2c55'
down_revision: Union[str, Sequence[str], None] = 'f7a3c1e94b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('cost_per_run_cents', sa.Integer(), nullable=False),
    sa.Column('max_task_budget_cents', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold_bps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('runs_total', sa.Integer(), nullable=False),
    sa.Column('runs_succeeded', sa.Integer(), nullable=False),
    sa.Column('runs_escalated', sa.Integer(), nullable=False),
    sa.Column('runs_failed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('confidence_bps', sa.Integer(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('criteria_results', sa.JSON(), nullable=False),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_runs_agent_user_id'), ['agent_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_runs_task_id'), ['task_id'], unique=False)

    # 自动生成的版本是 add_column(..., nullable=False) 且**没有默认值**——
    # 在已有数据的表上这会直接失败（Postgres 明确报错，SQLite 的 batch 重建
    # 也填不出值）。改成可移植的三步：先可空加列 → 回填 → 再置为非空。
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_criteria', sa.JSON(), nullable=True))
    op.execute("UPDATE tasks SET acceptance_criteria = '[]' WHERE acceptance_criteria IS NULL")
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('acceptance_criteria', existing_type=sa.JSON(), nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_agent', sa.Boolean(), nullable=True))
    # 存量用户都不是 agent
    op.execute("UPDATE users SET is_agent = FALSE WHERE is_agent IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_agent', existing_type=sa.Boolean(), nullable=False)
        batch_op.create_index(batch_op.f('ix_users_is_agent'), ['is_agent'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_agent'))
        batch_op.drop_column('is_agent')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('acceptance_criteria')

    with op.batch_alter_table('agent_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_status'))
        batch_op.drop_index(batch_op.f('ix_agent_runs_agent_user_id'))

    op.drop_table('agent_runs')
    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
