"""finance: settlement orders and splits

Revision ID: 79d8990fad5a
Revises: 5fdf27d6d8a1
Create Date: 2026-08-24 03:48:30.651003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79d8990fad5a'
down_revision: Union[str, Sequence[str], None] = '5fdf27d6d8a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('custody_ref', sa.String(length=80), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_orders_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_orders_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_orders_task_id'), ['task_id'], unique=False)

    op.create_table('settlement_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payee_user_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_splits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_splits_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_splits_payee_user_id'), ['payee_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement_splits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_splits_payee_user_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_splits_order_id'))

    op.drop_table('settlement_splits')
    with op.batch_alter_table('settlement_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_orders_task_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_orders_created_at'))
        batch_op.drop_index(batch_op.f('ix_settlement_orders_contract_id'))

    op.drop_table('settlement_orders')
    # ### end Alembic commands ###
