"""team accounts

Revision ID: c594b8444a39
Revises: edc1234d14bc
Create Date: 2026-09-18 06:59:48.748610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c594b8444a39'
down_revision: Union[str, Sequence[str], None] = 'edc1234d14bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('spend_limit_cents', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_members_team_id'), ['team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_members_user_id'), ['user_id'], unique=False)

    op.create_table('team_spend_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_spend_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_spend_requests_requester_id'), ['requester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_spend_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_team_spend_requests_team_id'), ['team_id'], unique=False)

    op.create_table('teams',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=120), nullable=False),
    sa.Column('tax_number', sa.String(length=40), nullable=False),
    sa.Column('license_images', sa.Text(), nullable=False),
    sa.Column('verify_status', sa.String(length=12), nullable=False),
    sa.Column('verify_reason', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_verify_status'), ['verify_status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_team', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_team = FALSE WHERE is_team IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_team', existing_type=sa.Boolean(), nullable=False)
        batch_op.create_index(batch_op.f('ix_users_is_team'), ['is_team'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_team'))
        batch_op.drop_column('is_team')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_verify_status'))
        batch_op.drop_index(batch_op.f('ix_teams_owner_id'))

    op.drop_table('teams')
    with op.batch_alter_table('team_spend_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_spend_requests_team_id'))
        batch_op.drop_index(batch_op.f('ix_team_spend_requests_status'))
        batch_op.drop_index(batch_op.f('ix_team_spend_requests_requester_id'))

    op.drop_table('team_spend_requests')
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_team_members_team_id'))

    op.drop_table('team_members')
    # ### end Alembic commands ###
