"""ip clauses and outcome pricing

Revision ID: edc1234d14bc
Revises: f63cac182b4f
Create Date: 2026-09-18 03:21:07.190710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc1234d14bc'
down_revision: Union[str, Sequence[str], None] = 'f63cac182b4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 同 V73/V75：自动生成的是无默认值的 NOT NULL，在已有数据的表上
    # Postgres 会直接失败。可移植三步：可空加列 → 回填 → 置非空。
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_cents', sa.Integer(), nullable=True))
    op.execute("UPDATE contracts SET bonus_cents = 0 WHERE bonus_cents IS NULL")
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.alter_column('bonus_cents', existing_type=sa.Integer(), nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_assignment', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('bonus_cents', sa.Integer(), nullable=True))
    # IPC-004 存量任务没有归属约定。回填成 'assign' 会**替当事人做一个
    # 他们从没同意过的决定**，所以回填空串——它们的合同已经签了，
    # 归属按签署时的条款（那时也没有这一段）走，新任务才强制选。
    op.execute("UPDATE tasks SET ip_assignment = '' WHERE ip_assignment IS NULL")
    op.execute("UPDATE tasks SET bonus_cents = 0 WHERE bonus_cents IS NULL")
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('ip_assignment', existing_type=sa.String(length=24),
                              nullable=False)
        batch_op.alter_column('bonus_cents', existing_type=sa.Integer(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('bonus_cents')
        batch_op.drop_column('ip_assignment')

    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_column('bonus_cents')

    # ### end Alembic commands ###
