"""certification verification

Revision ID: f63cac182b4f
Revises: f8e38000c6c7
Create Date: 2026-09-18 03:01:47.783042

"""
from typing import Sequence, Union

from alembic import op
import json
from datetime import datetime, timezone

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63cac182b4f'
down_revision: Union[str, Sequence[str], None] = 'f8e38000c6c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('holder_name', sa.String(length=50), nullable=False),
    sa.Column('cert_number', sa.String(length=60), nullable=False),
    sa.Column('issuer', sa.String(length=80), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('certification_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certification_applications_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_certification_applications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_certification_applications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sensitive', sa.Boolean(), nullable=True))
    op.execute("UPDATE uploaded_files SET sensitive = FALSE WHERE sensitive IS NULL")
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('sensitive', existing_type=sa.Boolean(), nullable=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_sensitive'), ['sensitive'], unique=False)

    # ### end Alembic commands ###

    # ---------------------------------------------------------------- CERT-006
    # 存量 `users.certifications` 是**用户自己 POST 进去的**，没有任何人看过
    # 任何一张证件。三个选项里必须选一个：
    #
    #   保留        → 那些没核过的资质继续生效，这一批白做
    #   直接清空    → 门关上了，但用户的资质凭空消失，不知道发生了什么
    #   转成待补申请 → 门关上了，用户看得到「待补充证件材料」  ← 选这个
    #
    # 准入立刻收紧，同时用户不至于一头雾水。
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT id, certifications FROM users "
        "WHERE certifications IS NOT NULL AND certifications != '[]'"
    )).fetchall()
    now = datetime.now(timezone.utc)
    for user_id, raw in rows:
        try:
            names = json.loads(raw) if isinstance(raw, str) else (raw or [])
        except (TypeError, ValueError):
            names = []
        for name in names:
            if not isinstance(name, str) or not name.strip():
                continue
            conn.execute(sa.text(
                "INSERT INTO certification_applications "
                "(user_id, name, holder_name, cert_number, issuer, images, status, "
                " decision_reason, created_at) "
                "VALUES (:uid, :name, '', '', '', :images, 'pending', :reason, :now)"
            ), {"uid": user_id, "name": name[:30], "images": "[]", "now": now,
                "reason": "历史自助添加的资质，需补充证件影像并经平台核验后方可生效"})
    # 清空快照字段：准入判断改读申请表，但这里也一并清掉，
    # 免得任何仍在读旧字段的代码路径被它误导
    conn.execute(sa.text("UPDATE users SET certifications = '[]'"))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_sensitive'))
        batch_op.drop_column('sensitive')

    with op.batch_alter_table('certification_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certification_applications_user_id'))
        batch_op.drop_index(batch_op.f('ix_certification_applications_status'))
        batch_op.drop_index(batch_op.f('ix_certification_applications_name'))

    op.drop_table('certification_applications')
    # ### end Alembic commands ###
