"""early cooperation ventures

Revision ID: f8e38000c6c7
Revises: 0799686c9be7
Create Date: 2026-09-18 02:48:46.902949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e38000c6c7'
down_revision: Union[str, Sequence[str], None] = '0799686c9be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('valued_cents', sa.Integer(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirm_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contributions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contributions_venture_id'), ['venture_id'], unique=False)

    op.create_table('distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venture_id', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('share_snapshot', sa.JSON(), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distributions_venture_id'), ['venture_id'], unique=False)

    op.create_table('venture_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venture_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('risk_disclosure_version', sa.String(length=20), nullable=False),
    sa.Column('risk_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('venture_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venture_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venture_members_venture_id'), ['venture_id'], unique=False)

    op.create_table('ventures',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('founder_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('ventures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventures_founder_id'), ['founder_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventures_status'), ['status'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_venture', sa.Boolean(), nullable=True))
    # 与 V73 同一条：自动生成的是无默认值的 NOT NULL，在已有数据的表上
    # Postgres 会直接失败。可移植三步：可空加列 → 回填 → 置非空。
    op.execute("UPDATE users SET is_venture = FALSE WHERE is_venture IS NULL")
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_venture', existing_type=sa.Boolean(), nullable=False)
        batch_op.create_index(batch_op.f('ix_users_is_venture'), ['is_venture'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_is_venture'))
        batch_op.drop_column('is_venture')

    with op.batch_alter_table('ventures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventures_status'))
        batch_op.drop_index(batch_op.f('ix_ventures_founder_id'))

    op.drop_table('ventures')
    with op.batch_alter_table('venture_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venture_members_venture_id'))
        batch_op.drop_index(batch_op.f('ix_venture_members_user_id'))

    op.drop_table('venture_members')
    with op.batch_alter_table('distributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distributions_venture_id'))

    op.drop_table('distributions')
    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contributions_venture_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_user_id'))
        batch_op.drop_index(batch_op.f('ix_contributions_status'))

    op.drop_table('contributions')
    # ### end Alembic commands ###
